[package]
name = "rustchatui"
version = "0.1.1"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "chatui"
path = "src/main.rs"

[dependencies]
axum = "0.7.4"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["fs", "cors"] }
anyhow = "1"